=== bertcarnell/fry9c/inst/extdata/FR_Y-9C.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="FRY9C" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="schedule" minOccurs="1" maxOccurs="unbounded" type="_Schedules"/>
            </xsd:sequence>
            <xsd:attribute name="date" type="xsd:string"/>
            <xsd:attribute name="omb_number" type="xsd:string"/>
            <xsd:attribute name="title" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="_Schedules">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="component" minOccurs="1" maxOccurs="unbounded" type="_Components"/>
            </xsd:sequence>
            <xsd:attribute name="desig" type="xsd:string"/>
            <xsd:attribute name="title" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="_Components">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="component" minOccurs="0" maxOccurs="unbounded" type="_Components"/>
            </xsd:sequence>
            <xsd:attribute name="num" type="xsd:string"/>
            <xsd:attribute name="name" type="xsd:string"/>
            <xsd:attribute name="key" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bertcarnell/fry9c/inst/extdata/FR_Y-9C20210131.xml
<FRY9C date="20210131" omb_number="7100-0128" title="Consolidated Financial Statements for Holding Companies—FR Y-9C"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="FR_Y-9C.xsd">
  <schedule desig="HI" title="Consolidated Income Statement">
    <component num="1." name="Interest Income" key="NA">
      <component num="1.a." name="Interest and fee income on loans" key="NA">
        <component num="1.a.(1)" name="In domestic offices" key="NA">
          <component num="1.a.(1)(a)" name="Loans secured by 1– 4 family residential properties" key="BHCK4435"/>
          <component num="1.a.(1)(b)" name="All other loans secured by real estate" key="BHCK4436"/>
          <component num="1.a.(1)(c)" name="All other loans" key="BHCKF821"/>
        </component>
        <component num="1.a.(2)" name="In foreign offices, Edge and Agreement subsidiaries, and IBFs" key="BHCK4059"/>
      </component>
      <component num="1.b." name="Income from lease financing receivables" key="BHCK4065"/>
      <component num="1.c." name="Interest income on balances due from depository institutions1" key="BHCK4115"/>
      <component num="1.d." name="Interest and dividend income on securities" key="NA">
        <component num="1.d.(1)" name="U.S. Treasury securities and U.S. government agency obligations (excluding mortgage-backed securities)" key="BHCKB488"/>
        <component num="1.d.(2)" name="Mortgage-backed securities" key="BHCKB489"/>
        <component num="1.d.(3)" name="All other securities" key="BHCK4060"/>
      </component>
      <component num="1.e." name="Interest income from trading assets" key="BHCK4069"/>
      <component num="1.f." name="Interest income on federal funds sold and securities purchased under agreements to resell" key="BHCK4020"/>
      <component num="1.g." name="Other interest income" key="BHCK4518"/>
      <component num="1.h." name="Total interest income" key="BHCK4107"/>
    </component>
    <component num="2." name="Interest expense" key="NA">
      <component num="2.a." name="Interest on deposits" key="NA">
        <component num="2.a.(1)" name="In domestic offices" key="NA">
          <component num="2.a.(1)(a)" name="Time deposits of $250,000 or less" key="BHCKHK03"/>
          <component num="2.a.(1)(b)" name="Time deposits of more than $250,000" key="BHCKHK04"/>
          <component num="2.a.(1)(c)" name="Other deposits" key="BHCK6761"/>
        </component>
        <component num="2.a.(2)" name="In foreign offices, Edge and Agreement subsidiaries, and IBFs" key="BHCK4172"/>
      </component>
      <component num="2.b." name="Expense on federal funds purchased and securities sold under agreements to repurchase" key="BHCK4180"/>
      <component num="2.c." name="Interest on trading liabilities and other borrowed money (excluding subordinated notes and debentures)" key="BHCK4185"/>
      <component num="2.d." name="Interest on subordinated notes and debentures and on mandatory convertible securities" key="BHCK4397"/>
      <component num="2.e." name="Other interest expense" key="BHCK4398"/>
      <component num="2.f." name="Total interest expense" key="BHCK4073"/>
    </component>
    <component num="3." name="Net interest income" key="BHCK4074"/>
    <component num="4." name="Provision for loan and lease losses" key="BHCK4230"/>
    <component num="5." name="Noninterest income" key="NA">
      <component num="5.a." name="Income from fiduciary activities" key="BHCK4070"/>
      <component num="5.b." name="Service charges on deposit accounts in domestic offices" key="BHCK4483"/>
      <component num="5.c." name="Trading revenue" key="BHCKA220"/>
      <component num="5.d." name="" key="NA">
        <component num="5.d.(1)" name="Fees and commissions from securities brokerage" key="BHCKC886"/>
        <component num="5.d.(2)" name="Investment banking, advisory, and underwriting fees and commissions" key="BHCKC888"/>
        <component num="5.d.(3)" name="Fees and commissions from annuity sales" key="BHCKC887"/>
        <component num="5.d.(4)" name="Underwriting income from insurance and reinsurance activities" key="BHCKC386"/>
        <component num="5.d.(5)" name="Income from other insurance activities" key="BHCKC387"/>
      </component>
      <component num="5.e." name="Venture capital revenue" key="BHCKB491"/>
      <component num="5.f." name="Net servicing fees" key="BHCKB492"/>
      <component num="5.g." name="Net securitization income" key="BHCKB493"/>
      <component num="5.h." name="Not Applicable" key="NA"/>
      <component num="5.i." name="Net gains (losses) on sales of loans and lease" key="BHCK8560"/>
      <component num="5.j." name="Net gains (losses) on sales of other real estate owned" key="BHCK8561"/>
      <component num="5.k." name="Net gains (losses) on sales of other assets" key="BHCKB496"/>
      <component num="5.l." name="Other noninterest income" key="BHCKB497"/>
      <component num="5.m." name="Total noninterest income" key="BHCK4079"/>
    </component>
    <component num="6." name="Realized Gains" key="NA">
      <component num="6.a." name="Realized gains (losses) on held-to-maturity securities" key="BHCK3521"/>
      <component num="6.b." name="Realized gains (losses) on available-for-sale securities" key="BHCK3196"/>
    </component>
    <component num="7." name="Noninterest expense" key="NA">
      <component num="7.a." name="Salaries and employee benefits" key="BHCK4135"/>
      <component num="7.b." name="Expenses of premises and fixed assets (net of rental income) (excluding salaries and employee benefits and mortgage interest)" key="BHCK4217"/>
      <component num="7.c." name="" key="NA">
        <component num="7.c.(1)" name="Goodwill impairment losses" key="BHCKC216"/>
        <component num="7.c.(2)" name="Amortization expense and impairment losses for other intangible assets" key="BHCKC232"/>
      </component>
      <component num="7.d." name="Other noninterest expense" key="BHCK4092"/>
      <component num="7.e." name="Total noninterest expense" key="BHCK4093"/>
    </component>
    <component num="8." name="" key="NA">
      <component num="8.a." name="Income (loss) before unrealized holding gains (losses) on equity securities not held for trading, applicable income taxes, and discontinued operations" key="BHCKHT69"/>
      <component num="8.b." name="Unrealized holding gains (losses) on equity securities not held for trading" key="BHCKHT70"/>
      <component num="8.c." name="Income (loss) before applicable income taxes and discontinued operations" key="BHCK4301"/>
    </component>
    <component num="9." name="Applicable income taxes (foreign and domestic)" key="BHCK4302"/>
    <component num="10." name="Income (loss) before discontinued operations" key="BHCK4300"/>
    <component num="11." name="Discontinued operations, net of applicable income taxes" key="BHCKFT28"/>
    <component num="12." name="Net income (loss) attributable to holding company and noncontrolling (minority) interests" key="BHCKG104"/>
    <component num="13." name="LESS: Net income (loss) attributable to noncontrolling (minority) interests" key="BHCKG103"/>
    <component num="14." name="Net income (loss) attributable to holding company" key="BHCK4340"/>
  </schedule>
  <schedule desig="HI_Memo" title = "Consolidated Income Statement">
    <component num="5." name="Number of full-time equivalent employees at end of current period" key="BHCK4150"/>
    <component num="6." name="Other noninterest income" key="NA">
      <component num="6.a." name="Income and fees from the printing and sale of checks" key="BHCKC013"/>
      <component num="6.b." name="Earnings on/increase in value of cash surrender value of life insurance" key="BHCKC014"/>
      <component num="6.c." name="Income and fees from automated teller machines (ATMs)" key="BHCKC016"/>
      <component num="6.d." name="Rent and other income from other real estate owned" key="BHCK4042"/>
      <component num="6.e." name="Safe deposit box rent" key="BHCKC015"/>
      <component num="6.f." name="Bank card and credit card interchange fees" key="BHCKF555"/>
      <component num="6.g." name="Income and fees from wire transfers" key="BHCKT047"/>
    </component>
    <component num="7." name="Other noninterest expense" key="NA">
      <component num="7.a." name="Data processing expenses" key="BHCKC017"/>
      <component num="7.b." name="Advertising and marketing expenses" key="BHCK0497"/>
      <component num="7.c." name="Directors' fees" key="BHCK4136"/>
      <component num="7.d." name="Printing, stationery, and supplies" key="BHCKC018"/>
      <component num="7.e." name="Postage" key="BHCK8403"/>
      <component num="7.f." name="Legal fees and expenses" key="BHCK4141"/>
      <component num="7.g." name="FDIC deposit insurance assessments" key="BHCK4146"/>
      <component num="7.h." name="Accounting and auditing expenses" key="BHCKF556"/>
      <component num="7.i." name="Consulting and advisory expenses" key="BHCKF557"/>
      <component num="7.j." name="Automated teller machine (ATM) and interchange expenses" key="BHCKF558"/>
      <component num="7.k." name="Telecommunications expenses" key="BHCKF559"/>
      <component num="7.l." name="Other real estate owned expenses" key="BHCKY923"/>
      <component num="7.m." name="Insurance expenses (not included in employee expenses, premises and fixed assets expenses, and other real estate owned expenses)" key="BHCKY924"/>
    </component>
  </schedule>
  <schedule desig="HC" title="Consolidated Balance Sheet">
    <component num="1." name="Cash and balances due from depository institutions" key="NA">
      <component num="1.a." name="Noninterest-bearing balances and currency and coin" key="BHCK0081"/>
      <component num="1.b." name="Interest-bearing balances" key="NA">
